"""Single source of truth for experiment defaults."""

SCHEMA_VERSION = "1.0.0"

DEFAULTS: dict = {
    "schema_version": SCHEMA_VERSION,
    "model": "modernbert",
    "hf_model": "answerdotai/ModernBERT-base",
    "train_fraction": 1.0,
    "results_dir": "results",
    "data_dir": "datasets",
    "random_state": 42,
    "hard_slice_quantile": 0.8,
    "beta": 0.3,
    "theta": 0.2,
    "epochs": 6,
    "epochs_per_phase": 2,
    "batch_size": 32,
    "eval_batch_size": 64,
    "max_length": 256,
    "lr": 2.0e-5,
    "weight_decay": 1.0e-3,
    "warmup_ratio": 0.06,
    "imbalance_method": "inverse_freq_ce",
    "effective_num_beta": 0.9999,
    "dist_bal_tau": 1.0,
    "dist_bal_logit_bias": 0.1,
    "aug_target_min_count": 5,
    "aug_ratio": 0.25,
    "aug_random_swap": 0.2,
    "aug_random_delete": 0.1,
    "curriculum_method": "biois_discrete",
    "curriculum_beta": 0.5,
    "curriculum_q_low": 0.3,
    "curriculum_q_mid": 0.6,
    "curriculum_q_high": 0.95,
    "curriculum_n_steps": 6,
    "curriculum_alpha_decay": 10.0,
    "curriculum_soft_lambda_init": 0.25,
    "curriculum_soft_lambda_growth": 1.4,
    "curriculum_soft_lambda_max": 1.0,
    "curriculum_soft_min_weight": 1e-3,
    "curriculum_soft_stability_tol": 5e-3,
    "curriculum_soft_saturation_patience": 2,
    "curriculum_soft_max_effective_steps": 6,
    "curriculum_loss_scheme": "linear",
    "curriculum_lambda_init": 0.5,
    "curriculum_lambda_step": 0.5,
    "curriculum_lambda_mult": 1.0,
    "curriculum_lambda_max": None,
    "curriculum_lambda2": None,
    "curriculum_loss_prior_reliability": True,
    "curriculum_min_weight": 1e-3,
    "curriculum_loss_recompute_every": 2,
    "spdcl_n_bins": 5,
    "spdcl_curriculum_epochs": None,
    "spdcl_anneal_epochs": 1,
    "spdcl_norm_subsample": None,
    "b1_easy_fraction": 0.5,
    "b1_use_global_quantile": True,
    "class_balanced_loss": None,
    "cuda_device_id": 7,
    "docker_image": "bio-is-curriculum:latest",
    "docker_gpu_id": 7,
    "docker_cpus": 16,
    "docker_memory": "32g",
    "docker_container_workdir": "/app",
}
